modify readme and changelog in workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -92,6 +92,28 @@ jobs:
         export MAC_ASSET_ID=`sed -n 1p assets/macos-latest.txt`
         export MAC_ASSET_SHA_256=`sed -n 2p assets/macos-latest.txt`
 
+        if [ -z "${LINUX_ASSET_ID}" ]; then
+            echo "Error: Invalid linux asset id: $LINUX_ASSET_ID"
+            exit 1
+        fi
+        if grep -w "$VERSION" CHANGELOG.md; then
+            echo "Error: $VERSION already released, found a changelog entry for it."
+            exit 1
+        fi
+
+        DATE=`date +%Y-%m-%d`
+        cat >>CHANGELOG.md <<EOL
+
+        ## $VERSION ($DATE)
+        $CHANGELOG
+        EOL
+
+        sed -i -e 's/assets\/[0-9][0-9]* /assets\/'"$LINUX_ASSET_ID"' /g' README.md
+
+        git add CHANGELOG.md README.md
+        git commit -m "Release $VERSION"
+        git push --set-upstream origin master
+
         curl -X POST https://api.github.com/repos/eb-rubenespinosa/brew_test/dispatches \
           -H 'Accept: application/vnd.github.everest-preview+json' \
           -H "Authorization: token ${{secrets.PAT_TOKEN}}" \
